### PR TITLE
add tests, plus to multiplication

### PR DESCRIPTION
**Pull request by jasmineirx**
I was trying to follow the logic in this function, since there are a lot of different combinations of arguments accepted. I added a few tests as examples of ways to supply these arguments, increasing the test coverage of the file to 100%.

I found what I think is an error: an addition should have been changed to a multiplication.

### CODE REVIEW

**Comment by roninsightrx** [comment]
Oh wow, completely missed that. Thx!

**Comment by roninsightrx** [comment]
I just pushed up some changes, seems there is a conflict now.

**Review by roninsightrx — APPROVED** [review]
lgtm

**Comment by jasmineirx** [comment]
I feel like theres a clever way to create a sub-function that handles all the logic for both apply_lagtime and apply_duration_scale, except passing either `*` or `+` as an argument, but the functions are structured just *slightly* different that it would take a bit of time.

**Pull request merged**
